"""LLM-powered cover letter generation for application packs."""

from __future__ import annotations

import json
import logging
import urllib.error
import urllib.request
from typing import Any

from career_job_search.cvs.matching import variant_markdown_path

logger = logging.getLogger(__name__)

OLLAMA_BASE_URL = "http://127.0.0.1:11434"
OLLAMA_CHAT_URL = f"{OLLAMA_BASE_URL}/api/chat"
DEFAULT_MODEL = "qwen3.5:35b-a3b-fast"
MAX_RESPONSE_BYTES = 256 * 1024

COVER_LETTER_SYSTEM = (
    "You are a professional cover letter writer. "
    "Given a CV and a job description, write a tailored cover letter (250-400 words) that:\n"
    "1. Addresses the hiring manager\n"
    "2. Opens with a strong hook connecting the candidate's experience to the role\n"
    "3. Highlights 2-3 specific achievements from the CV relevant to the job\n"
    "4. Explains why the candidate is interested in the company and role\n"
    "5. Closes with a call to action\n"
    "6. Uses professional but warm language\n\n"
    "Do NOT invent facts not present in the CV. "
    "Do NOT mention AI tools in the letter. "
    "Do NOT use placeholders like [Your Name]. "
    "Write in the candidate's voice."
)


def _local_opener() -> urllib.request.OpenerDirector:
    return urllib.request.build_opener(urllib.request.ProxyHandler({}))


def generate_cover_letter(
    title: str,
    company: str,
    description: str,
    cv_variant: str,
    variants: dict[str, Any],
    location: str = "",
    config: dict[str, Any] | None = None,
) -> str | None:
    """Generate a cover letter using local Ollama.

    Returns markdown text or None on failure.
    """
    if config is None:
        config = {}

    model = config.get("model", DEFAULT_MODEL)

    cv_text = ""
    try:
        md_path = variant_markdown_path(cv_variant, variants)
        cv_text = md_path.read_text(encoding="utf-8")[:4000]
    except Exception as exc:
        logger.debug("Could not read CV for cover letter: %s", exc)
        cv_text = f"Candidate CV variant: {cv_variant}"

    description = (description or "")[:3000]

    user_prompt = (
        f"Job Title: {title}\n"
        f"Company: {company}\n"
        f"Location: {location}\n\n"
        f"Job Description:\n{description}\n\n"
        f"---\n\n"
        f"CV ({cv_variant}):\n{cv_text}\n\n"
        f"Please write a tailored cover letter for this application."
    )

    body = json.dumps(
        {
            "model": model,
            "stream": False,
            "messages": [
                {"role": "system", "content": COVER_LETTER_SYSTEM},
                {"role": "user", "content": user_prompt},
            ],
            "options": {"temperature": 0.2, "num_predict": 900},
        },
        ensure_ascii=False,
    ).encode("utf-8")

    request = urllib.request.Request(  # noqa: S310
        OLLAMA_CHAT_URL,
        data=body,
        headers={"Accept": "application/json", "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with _local_opener().open(request, timeout=120) as response:
            content = response.read(MAX_RESPONSE_BYTES + 1)
    except (OSError, urllib.error.URLError) as exc:
        logger.warning("Cover letter generation failed (Ollama unreachable): %s", exc)
        return None
    if len(content) > MAX_RESPONSE_BYTES:
        logger.warning("Cover letter response exceeded size limit")
        return None
    try:
        payload = json.loads(content.decode("utf-8"))
        draft = str((payload.get("message") or {}).get("content") or "").strip()
    except (UnicodeDecodeError, json.JSONDecodeError, AttributeError) as exc:
        logger.warning("Cover letter response was invalid: %s", exc)
        return None
    if not draft:
        logger.warning("Cover letter response was empty")
        return None

    return f"# Cover Letter: {title} at {company}\n\n{draft}\n\n---\n*Generated by {model}*"
